module.exports = {
    listeningHeaders: [
        { label: "שלוחה", value: "extension", order: 5 },
        { label: "השמעה", value: "listening", order: 6 },
        { label: "טלפון", value: "phone", order: 7 },
        { label: "סוג זיהוי", value: "identityType", order: 8 },
        { label: "מספר זיהוי", value: "identityNumber", order: 3 },
        { label: "שם", value: "name", order: 4 },
        { label: "עברי", value: "hebrew", order: 2 },
        { label: "תאריך", value: "date", order: 1, format: "date" },
        { label: "שעת התחלה", value: "startTime", order: 9, format: "time" },
        { label: "נקודת התחלה", value: "startPoint", order: 11 },
        { label: "נקודת יציאה", value: "endPoint", order: 12 },
        { label: "שעת יציאה", value: "endTime", order: 10, format: "time" },
        { label: "סה''כ דקות", value: "seconds", order: 13, format: "sec2min" },
    ],
    lessonHeaders: [
        { label: "שלוחה", value: "extension" },
        { label: "שם הודעה", value: "messageName" },
    ],
    studentHeaders: [
        { label: "תעודת זהות", value: "identityNumber" },
        { label: "שם", value: "name" },
        { label: "מחזור", value: "grade" },
        { label: "מספר כיתה", value: "classNum" },
        { label: "מגמה", value: "megama" },
    ],
    confHeaders: [
        { label: "שלוחה", value: "extension" },
        { label: "שם השלוחה", value: "extensionName" },
        { label: "טלפון", value: "phone" },
        { label: "סוג זיהוי", value: "identityType" },
        { label: "מספר זיהוי", value: "identityNumber" },
        { label: "שם", value: "name" },
        { label: "תאריך עברי", value: "hebrew" },
        { label: "תאריך", value: "date", format: "date" },
        { label: "שעת כניסה", value: "startTime", format: "time" },
        { label: "שעת יציאה", value: "endTime", format: "time" },
        { label: "סך הכל זמן", value: "seconds", format: "sec2min" },
        { label: "חדר ועידה", value: "confRoom" },
        { label: "סוג כניסה", value: "enterType" },
    ],
    userHeaders: [
        { value: "name", label: "שם משתמש" },
        { value: "email", label: "דוא''ל" },
        { value: "isAdmin", label: "מנהל" },
        { value: "listening", label: "האזנה" },
        { value: "conf", label: "ועידה" },
        { value: "lesson", label: "שיעורים" },
        { value: "student", label: "תלמידות" },
    ],
    fileHeaders: [
        { value: "fileName", label: "שם הקובץ" },
        { value: "createdAt", label: "הועלה בתאריך", format: "datetime" },
    ],
    yemotPlaybackHeaders: [
        { value: "Folder", label: "שלוחה" },
        { value: "Current", label: "השמעה" },
        { value: "Phone", label: "טלפון" },
        { value: "IdType", label: "סוג זיהוי" },
        { value: "EnterId", label: "מספר זיהוי" },
        { value: "ValName", label: "שם" },
        { value: "EnterHebrewDate", label: "עברי" },
        { value: "EnterDate", label: "תאריך" },
        { value: "EnterTime", label: "שעת התחלה" },
        { value: "ExitTime", label: "שעת סיום" },
        { value: "PositionPlay", label: "נקודת התחלה" },
        { value: "PositionStop", label: "נקודת יציאה" },
        { value: "TimeTotal", label: "סה''כ שניות" },
    ],
    yemotConfBridgeHeaders: [
        { value: "Folder", label: "שלוחה" },
        { value: "title", label: "שם השלוחה" },
        { value: "Phone", label: "טלפון" },
        { value: "IdType", label: "סוג זיהוי" },
        { value: "EnterId", label: "מספר זיהוי" },
        { value: "ValName", label: "שם" },
        { value: "EnterHebrewDate", label: "תאריך עברי" },
        { value: "EnterDate", label: "תאריך" },
        { value: "EnterTime", label: "שעת כניסה" },
        { value: "ExitTime", label: "שעת יציאה" },
        { value: "ConfBridge", label: "חדר ועידה" },
        { value: "Type", label: "סוג כניסה" },
        { value: "TimeTotal", label: "סך הכל זמן" },
    ],
    pageSize: 10,
    graphNumberOfDays: 14,
};
