module.exports = {
    lessonHeaders: [
        { label: "שלוחה", value: "extension" },
        { label: "שם הודעה", value: "messageName" },
    ],
    studentHeaders: [
        { label: "תעודת זהות", value: "identityNumber" },
        { label: "שם", value: "name" },
        { label: "מחזור", value: "grade" },
        { label: "מספר כיתה", value: "classNum" },
        { label: "מגמה", value: "megama" },
    ],
    userHeaders: [
        { value: "name", label: "שם משתמש" },
        { value: "email", label: "דוא''ל", editable: true },
        { value: "password", label: "סיסמא", editable: true, hidden: true },
        { value: "yemotUsername", label: "שם משתמש לימות המשיח", editable: true, hidden: true },
        { value: "yemotPassword", label: "סיסמא לימות המשיח", editable: true, hidden: true },
        { value: "yemotIsPrivate", label: "חיבור פרטי לימות", editable: true, hidden: true },
        { value: "isPaid", label: "האם שילם?", editable: true, hidden: true },
        { value: "isAdmin", label: "מנהל" },
        { value: "listening", label: "האזנה" },
        { value: "conf", label: "ועידה" },
        { value: "lesson", label: "שיעורים" },
        { value: "student", label: "תלמידות" },
    ],
    fileHeaders: [
        { value: "fileName", label: "שם הקובץ" },
        { value: "createdAt", label: "הועלה בתאריך", format: "datetime" },
    ],
    yemotPlaybackHeaders: [
        { value: "Folder", label: "שלוחה" },
        { value: "Current", label: "השמעה" },
        { value: "Phone", label: "טלפון" },
        { value: "IdType", label: "סוג זיהוי" },
        { value: "EnterId", label: "מספר זיהוי" },
        { value: "ValName", label: "שם" },
        { value: "EnterHebrewDate", label: "עברי" },
        { value: "EnterDate", label: "תאריך", format: "date" },
        { value: "EnterTime", label: "שעת התחלה", format: "time" },
        { value: "ExitTime", label: "שעת סיום", format: "time" },
        { value: "PositionPlay", label: "נקודת התחלה" },
        { value: "PositionStop", label: "נקודת יציאה" },
        { value: "TimeTotal", label: "סה''כ שניות", format: "sec2min" },
    ],
    yemotConfBridgeHeaders: [
        { value: "Folder", label: "שלוחה" },
        { value: "title", label: "שם השלוחה" },
        { value: "Phone", label: "טלפון" },
        { value: "IdType", label: "סוג זיהוי" },
        { value: "EnterId", label: "מספר זיהוי" },
        { value: "ValName", label: "שם" },
        { value: "EnterHebrewDate", label: "תאריך עברי" },
        { value: "EnterDate", label: "תאריך", format: "date" },
        { value: "EnterTime", label: "שעת כניסה", format: "time" },
        { value: "ExitTime", label: "שעת יציאה", format: "time" },
        { value: "ConfBridge", label: "חדר ועידה" },
        { value: "Type", label: "סוג כניסה" },
        { value: "TimeTotal", label: "סך הכל זמן", format: "sec2min" },
    ],
    pageSize: 10,
    graphNumberOfDays: 14,
};
