image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install
      cd client
      npm install
  - command: npm run dev
  - command: |
      cd client 
      npm start

ports:
  - port: 8000
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
