export const reportTypeMapping = {
    listening: "האזנה",
    conf: "ועידה",
    record: "שיעורים מוקלטים",
    listening_And_conf: "משולב האזנה וועידה",
    listeningByDate: "האזנה לפי תאריך",
    listeningPercent: "האזנה - אחוזים",
    confPercent: "ועידה - אחוזים",
    recordPercent: "שיעורים מוקלטים - אחוזים",
    listening_And_confPercent: " משולב האזנה וועידה - אחוזים",
    listeningByDatePercent: "האזנה לפי תאריך - אחוזים",
    listeningGrade: "האזנה - ציונים",
    confGrade: "ועידה - ציונים",
    recordGrade: "שיעורים מוקלטים - ציונים",
    listening_And_confGrade: "משולב האזנה וועידה - ציונים",
    listeningByDateGrade: "האזנה לפי תאריך - ציונים",
};
