export default [
    {
        url: "dataByKlassOrMegama",
        title: "כיתה או מגמה",
        filterFields: ["singleKlass", "singleMegama", "lessonWithAll", "dateRange"],
        isAdmin: false,
        reportTypes: ["listening", "conf", "record"],
    },
    // {
    //     url: "dataByKlassAndLesson",
    //     title: "כיתה או מגמה ומקצוע",
    //     filterFields: ["singleKlass", "singleMegama", "singleLesson", "singleStudent", "dateRange"],
    //     isAdmin: false,
    //     reportTypes: ["listening", "conf", "record", "listeningByDate"],
    // },
    {
        url: "multipleDataByKlassAndLesson",
        title: "כיתה או מגמה ומקצוע",
        filterFields: ["singleKlass", "singleMegama", "lessonWithAll", "singleStudent", "dateRange"],
        isAdmin: false,
        reportTypes: [
            "listening",
            "conf",
            "record",
            "listening_And_conf",
            "listeningByDate",
            "listeningPercent",
            "confPercent",
            "recordPercent",
            "listening_And_confPercent",
            "listeningByDatePercent",
            "listeningGrade",
            "confGrade",
            "recordGrade",
            "listening_And_confGrade",
            "listeningByDateGrade",
        ],
    },
    {
        url: "diploma",
        title: "הנפקת תעודות לתלמידות",
        filterFields: ["singleKlass", "singleMegama", "lessonWithAll", "singleStudent", "dateRange"],
        isAdmin: false,
        reportTypes: ["listening", "conf", "record", "listeningByDate"],
    },
    {
        url: "listeningByKlassPerStudent",
        title: "דוח כללי לכיתה",
        filterFields: ["singleKlass", "dateRange"],
        isAdmin: false,
    },
];
